# Generated by Django 6.0.3 on 2026-03-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('ordine_scaletta', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('punteggio_totale', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Opzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=100)),
                ('is_corretta', models.BooleanField(default=False)),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opzioni', to='quiz_engine.canzone')),
            ],
        ),
        migrations.CreateModel(
            name='RispostaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_impiegato_ms', models.IntegerField()),
                ('punti_guadagnati', models.IntegerField(default=0)),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_engine.canzone')),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_engine.giocatore')),
            ],
            options={
                'unique_together': {('giocatore', 'canzone')},
            },
        ),
    ]
