# Generated by Django 6.0.3 on 2026-03-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canzone',
            name='testo_domanda',
            field=models.TextField(default='Che canzone è questa?'),
        ),
        migrations.CreateModel(
            name='StatoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('PREPARAZIONE', 'Schermata Iniziale'), ('DOMANDA', 'Canzone in corso'), ('CLASSIFICA', 'Classifica della canzone'), ('PODIO', 'Podio Finale')], default='PREPARAZIONE', max_length=20)),
                ('canzone_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_engine.canzone')),
            ],
            options={
                'verbose_name_plural': 'Stato Quiz',
            },
        ),
    ]
