# Generated by Django 6.0.3 on 2026-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_engine', '0002_canzone_testo_domanda_statoquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statoquiz',
            name='fase',
            field=models.CharField(choices=[('PREPARAZIONE', 'Schermata Iniziale'), ('LANCIO', 'Messaggio preparatevi inviato'), ('DOMANDA', 'Canzone in corso'), ('CLASSIFICA', 'Classifica della canzone'), ('PODIO', 'Podio Finale')], default='PREPARAZIONE', max_length=20),
        ),
    ]
